"use client";

import styles from "../../../styles/demo.module.scss";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Suspense } from "react";
import { Canvas, useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
export default function Demo() {
  /*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  */
  const group = useRef();
  const model = useLoader(GLTFLoader, "./models/hycodev.gltf");
  return (
    <Canvas className={styles.container}>
      <group ref={group} dispose={null}>
        <primitive object={model.scene} scale={1} />
      </group>
    </Canvas>
  );
}
// useGLTF.preload("./models/hycodev.gltf");
