export const Staff = [
  // {
  //     name: "",
  //     title: "",
  //     link: "",
  //     image: "",
  //     role: "",
  // },
  {
    name: "Zhi Zhang",
    title: "Postdoctoral Researcher",
    link: "https://www.researchgate.net/profile/Zhi-Zhang-48",
    image: "/images/people/zhi_zhang.jpg",
    role: "Researchers",
  },
  {
    name: "Arash Bahari Kordabad",
    title: "Postdoctoral Researcher",
    link: "https://arashbaharik.github.io/",
    image: "/images/people/arash_bahari_kordabad.jpg",
    role: "Researchers",
  },
  {
    name: "Mahmoud Salamati",
    title: "Postdoctoral Researcher",
    link: "",
    image: "/images/people/mahmoud_salamati.jpeg",
    role: "Researchers",
  },

  {
    name: "Oliver Schön",
    title: "PhD Student",
    link: "https://oliverschon.com/",
    image: "/images/people/oliver_schon.jpg",
    role: "PhDs",
  },

  {
    name: "John Ingham",
    title: "PhD Student",
    link: "",
    image: "/images/people/john_ingham.jpg",
    role: "PhDs",
  },
  {
    name: "Anna Laino",
    title: "PhD Student",
    link: "",
    image: "/images/people/anna_laino.jpg",
    role: "PhDs",
  },
  {
    name: "Marco Lewis",
    title: "PhD Student",
    link: "https://marco-lewis.github.io/",
    image: "/images/people/marco_lewis.jpg",
    role: "PhDs",
  },
  {
    name: "Chenyu Ma",
    title: "PhD Student",
    link: "",
    image: "/images/people/chenyu_ma.jpg",
    role: "PhDs",
  },
  {
    name: "Mahdieh Zaker",
    title: "PhD Student",
    link: "",
    image: "/images/people/mahdieh_zaker.png",
    role: "PhDs",
  },
  {
    name: "Ernesto Casablanca",
    title: "PhD Student",
    link: "https://github.com/TendTo",
    image: "/images/people/ernesto_casablanca.jpg",
    role: "PhDs",
  },

  {
    name: "Negar Monir",
    title: "PhD Student",
    link: "https://scholar.google.com/citations?user=7UPvsPkAAAAJ&hl=en",
    image: "/images/people/negar_monir.png",
    role: "PhDs",
  },
  {
    name: "Viktorija Bezganovic",
    title: "Intern",
    link: "",
    image: "/images/people/viktorija_bezganovic.jpg",
    role: "Interns",
  },
  {
    name: "Andrew Wright",
    title: "Intern",
    link: "",
    image: "/images/people/andrew_wright.jpg",
    role: "Interns",
  },

  {
    name: "Odette Mejia",
    title: "Intern",
    link: "",
    image: "/images/people/odette_mejia.jpg",
    role: "Interns",
  },
  {
    name: "Dovydas Stepas Vilkevicius",
    title: "Intern",
    link: "",
    image: "/images/people/dovydas_vilkevicius.jpg",
    role: "Interns",
  },
  {
    name: "Andrea Da Col",
    title: "Intern",
    link: "https://github.com/andreadacol98",
    image: "/images/people/andrea_da_col.jpg",
    role: "Interns",
  },

  {
    name: "Birgit van Huijgevoort",
    title: "Postdoctoral Researcher",
    link: "https://www.tue.nl/en/research/researchers/birgit-van-huijgevoort",
    image: "/images/people/birgit_van_huijgevoort.jpg",
    role: "Researchers",
  },
];

export const PastMembers = [
  {
    name: "Akshay Gupta",
    title: "Now at Newcastle University",
    link: "",
    image: "/images/people/akshay_gupta.jpg",
    role: "Past Members",
  },
  {
    name: "Isaac Matthews",
    title: "Now Security Researcher at Hewlett Packard Enterprise",
    link: "",
    image: "/images/people/isaac_matthews.jpg",
    role: "Past Members",
  },
  {
    name: "Ali Salamati",
    title: "Now at Autonomous Reply",
    link: "https://scholar.google.com/citations?user=JTyBUf8AAAAJ&hl=en",
    image: "/images/people/ali_salamati.jpg",
    role: "Past Members",
  },
  {
    name: "Ben Wooding",
    title: "Postdoctoral Researcher",
    link: "https://woodingben.com/",
    image: "/images/people/ben_wooding.png",
    role: "Past Members",
  },

  {
    name: "Milad Kazemi",
    title: "Now a Postdoctoral Researcher at King's College London",
    link: "",
    image: "/images/people/milad_kazemi.jpg",
    role: "Past Members",
  },
  {
    name: "Mahdi Nazeri",
    title: "Now a PhD Student at Newcastle University",
    link: "",
    image: "/images/people/empty_profile.png",
    role: "Past Members",
  },
  {
    name: "Omid Akbarzadeh",
    title: "Now a PhD Student at Newcastle University",
    link: "https://scholar.google.com/citations?user=k-k51eUAAAAJ&hl=en",
    image: "/images/people/omid_akbarzadeh.png",
    role: "Past Members",
  },
  {
    name: "Behrad Samari",
    title: "Now a PhD Student at Newcastle University",
    link: "",
    image: "/images/people/empty_profile.png",
    role: "Past Members",
  },
];

export const Collaborators = [
  {
    name: "Alessandro Abate",
    title: "University of Oxford, UK",
    link: "https://scholar.google.co.uk/citations?user=yskbfM4AAAAJ&hl=en",
    image: "/images/people/allesandro_abate.jpg",
    role: "Collaborators",
  },
  {
    name: "Ben Wooding",
    title: "Now a Postdoctoral Researcher at Newcastle University",
    link: "https://woodingben.com/",
    image: "/images/people/ben_wooding.png",
    role: "Collaborators",
  },
  {
    name: "Masahiro Fujita",
    title: "University of Tokyo, JPN",
    link: "https://scholar.google.com/citations?user=tYabznkAAAAJ&hl=en",
    image: "/images/people/masahiro_fujita.jpg",
    role: "Collaborators",
  },
  {
    name: "Sofie Haesaert",
    title: "TU Eindhoven, NL",
    link: "https://www.sofiehaesaert.com/",
    image: "/images/people/sofie_haesaert.jpg",
    role: "Collaborators",
  },
  {
    name: "Pushpak Jagtap",
    title: "Robert Bosch Center for Cyber-Physical Systems, IND",
    link: "https://www.pushpakjagtap.com/",
    image: "/images/people/pusjpak_jagtap.jpg",
    role: "Collaborators",
  },
  {
    name: "Rupak Majumdar",
    title: "Max Planck Institute for Software Systems, GER",
    link: "https://people.mpi-sws.org/~rupak/",
    image: "/images/people/rupak_majumdar.jpg",
    role: "Collaborators",
  },
  {
    name: "Kaushik Mallik",
    title: "Institute of Science and Technology, AUT",
    link: "https://scholar.google.de/citations?user=CG04xrsAAAAJ&hl=en",
    image: "/images/people/kaushik_malik.jpg",
    role: "Collaborators",
  },
  {
    name: "Adnane Saoud",
    title: "CentraleSupelec, University Paris-Saclay, FRA",
    link: "https://sites.google.com/view/adnanesaoud/",
    image: "/images/people/adnane_saoud.jpg",
    role: "Collaborators",
  },
  {
    name: "Anne-Kathrin Schmuck",
    title: "Max Planck Institute for Software Systems, GER",
    link: "https://wp.mpi-sws.org/akschmuck/",
    image: "/images/people/anne_kathrin_schmuck.jpg",
    role: "Collaborators",
  },
  {
    name: "Fabio Somenzi",
    title: "UC Boulder, USA",
    link: "https://www.colorado.edu/ecee/fabio-somenzi",
    image: "/images/people/fabio_somenzi.png",
    role: "Collaborators",
  },
  {
    name: "Ashutosh Trivedi",
    title: "UC Boulder, USA",
    link: "https://astrivedi.github.io/www/index.html",
    image: "/images/people/ashutosh_trivedi.jpg",
    role: "Collaborators",
  },
  {
    name: "Paolo Zuliani",
    title: "Newcastle University, UK",
    link: "https://www.ncl.ac.uk/computing/staff/profile/paolozuliani.html",
    image: "/images/people/paolo_zuliani.jpg",
    role: "Collaborators",
  },
  {
    name: "Arabinda Ghosh",
    title: "Max Planck Institute for Software Systems, GER",
    link: "https://sites.google.com/view/arabindaghosh/",
    image: "/images/people/arabinda_ghosh.jpg",
    role: "Researchers",
  },
];
