name: Publish Website to Hosting

on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Move .htaccess
        run: mv .htaccess out/

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: hycodev.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
