name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Push To Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ..
          cd home/hycodev/htdocs
          rm -r hycodev
          git clone https://github.com/xQuazor/hycodev.git
          cd hycodev
          npm i
          npm run build
          pm2 delete 0
          pm2 start npm --name "hycodev" -- start
        
        
